<?php     
    echo'<!-- General CSS for PC and laptops -->';
    echo'<link rel = "stylesheet" href = "styles/style.css">';
    echo'<!-- CSS style for Phone -->';
    echo'<link rel = "stylesheet" href = "styles/PhoneResponsive.css" media="screen and (max-width: 480px)">';
    echo'<!-- CSS style for Low Resolution Ipad -->';
    echo'<link rel = "stylesheet" href = "styles/LowresIpadResponsive.css" media="(min-width: 481px) and (max-width: 767px)">';
    echo'<!-- CSS style for Ipad -->';
    echo'<link rel = "stylesheet" href = "styles/IpadResponsive.css" media="(min-width: 768px) and (max-width: 1180px)">';
?>